version: '3'

services: 
  authapi:
    build:
      dockerfile: ./docker/Dockerfile.dev
      context: .
    restart: always
    volumes:
      - .:/usr/src/auth
      - /usr/src/auth/node_modules
    environment: 
      - FORCE_COLOR=1
    ports:
      - 9230:9230
      - ${PORT}:${PORT}
    command: 
      - sh
      - -c
      - sleep 20 && npm run start:dev
    depends_on: 
      - psql

  psql:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
